language: node_js
node_js: 
  - "6.3.1"
before_install:
  - git clone https://github.com/cmacclang/cmacc-compiler.git
  - cd cmacc-compiler
  - npm install cmacc-compiler -g
  - yarn link
  - cd ..
install:
  - yarn 
  - yarn link cmacc-compiler